### ISSUE TITLE
Can't contact LDAP server

### ISSUE THREAD

**Issue by Gertiozuni** [fkote/ldap-laravel#1]
Hi, thanks for your effort on doing this starter. 

I am having an issue on this. This is the tree i created [https://i.imgur.com/a5UPakB.png](https://i.imgur.com/a5UPakB.png) . Here is my env file 
`ADLDAP_ACCOUNT_PREFIX=uid=
ADLDAP_ACCOUNT_SUFFIX=,ou=users,dc=example,dc=com
ADLDAP_CONTROLLERS=localhost
ADLDAP_PORT=10389
ADLDAP_BASEDN=dc=example,dc=com
ADLDAP_ADMIN_ACCOUNT_PREFIX=uid=
ADLDAP_ADMIN_ACCOUNT_SUFFIX=,ou=system
ADLDAP_ADMIN_USERNAME=admin
ADLDAP_ADMIN_PASSWORD=secret`
 . Nothing else changed. Also this is my connection on apache directory studio [https://i.imgur.com/4IlgM2v.png](https://i.imgur.com/4IlgM2v.png) , [https://i.imgur.com/wpfRwnX.png](https://i.imgur.com/wpfRwnX.png)

**Comment by fkote** [comment]
Hi, @Gertiozunim,

First of all, I am so sorry for the late reply. This was a personal project, I was not expecting anyone to use it. So, I did not have notifications enabled.

Now, I hope you have resolved the issue by now. If you haven't, I would like to help you. I compared your configuration to mine, it seems fine. The description is really general, but here are some ideas:

1. Enable LDAP in php.ini if you haven't already.
2. Test if you can bind to the LDAP server using raw PHP.

**Comment by Gertiozuni** [comment]
I already found my way around that long time ago. 
Thanks anyway 👍

**Comment by fkote** [comment]
If you remember what the problem was and how you solved it, please share it and close this issue.

Have a good one.
